name: CI/CD Dental

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "deployment" ]
  pull_request:
    branches: [ "deployment" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sshpass -p ${{secrets.SERVER_PASSWORD}} ssh -o StrictHostKeyChecking=no nhanvu@115.79.196.99 << EOF
          sudo su -
          echo ${{secrets.SERVER_PASSWORD}} | sudo -S command
          cd /home/nhanvu/work_space/dental/dental-fe
          git pull origin deployment
          sudo docker-compose -f docker-compose-staging.yml up -d --build
